### PR TITLE
Revert "DEBUG failed github-script"

### PR DESCRIPTION
**Pull request by atodorov**
This reverts commit 5f1cf1168ef6cde6b36e73f1124d612c11c1f318.

### CODE REVIEW

**Comment by atodorov** [comment]
@kiwitcms rebase

**Comment by atodorov** [comment]
@kiwitcms-bot rebase

**Comment by atodorov** [comment]
@kiwitcms help

**Comment by atodorov** [comment]
@kiwitcms help

**Comment by RMadjev** [comment]
@kiwitcms-bot help

**Comment by atodorov** [comment]
@kiwitcms-bot debug

**Comment by atodorov** [comment]
@kiwitcms-bot help

**Pull request merged**
